### ISSUE TITLE
Apache: File name too long: Cannot map GET

### ISSUE THREAD

**Issue by michaelscheel** [fooman/speedster#14]
If the list of resources is too long apache (on my environment > 1000 characters) filesystem checks will fail, resulting in a 403 error thrown.

**Comment by fooman** [comment]
This works as intended then. Either change your apache config or change the 2000 value here
https://github.com/fooman/speedster/blob/master/app/code/community/Fooman/Speedster/Block/Page/Html/Head.php#L201

**Comment by ExtensionsStore** [comment]
Should be a system config value. You pretty much have to be a system administrator to get this module working.
