### ISSUE TITLE
Magento 1.9.2.2 and tinemce in admin

### ISSUE THREAD

**Issue by quienti** [fooman/speedster#17]
On Magento 1.9.2.2 and TinyMce in admin

I have this error => Uncaught TypeError: p is not a function in tinymce.js after install this module

When I disable this module, it's works

Any idea to resolve my problem ?

Thanks

**Comment by No1Monkey** [comment]
I am currently having this same issue. do you mind me asking if and how you resolved this issue? Thank you in advance.

**Comment by anisagrebi** [comment]
can you please post how do you solved this problem please

**Comment by No1Monkey** [comment]
This is still an outstanding issue. If you work it out please let me know.

**Comment by No1Monkey** [comment]
On Magento 1.9.2.2/ Conflict between Fooman & TinyMce admin error: 
Uncaught TypeError: p is not a function in tinymce.js  

Fixed by adding:
app/code/community/fooman/speedster/block/page/head.php
line 32, before the if;

`//get the admin session
    	Mage::getSingleton('core/session', array('name'=>'adminhtml'));
    	//verify if the user is logged in to the backend
        if (Mage::getSingleton('admin/session')->isLoggedIn()) {
            return parent::getCssJsHtml();
        }`
