### ISSUE TITLE
How to manage versioning on merged files?

### ISSUE THREAD

**Issue by hashid** [fooman/speedster#19]
Hi, I would like to use versioning on the generated css and js files so that user's browser can be forced to refresh cache. How to do this with speedster?

**Comment by tmos** [comment]
:+1: and it would be a nice option for refreshing files even if we don't make any modification, but just change the minification options (I think at the moment, it doesn't reprocess the file, does it ?)

**Comment by fooman** [comment]
Versioning happens automatically based on the last modified timestamp of the files being minified. In this url skin/m/1232681243/... 1232681243 is the timestamp. The only thing you would need to do after a file change is to refresh your html block cache within Magento.

If you really must force a reminification only, you can delete the contents of var/minifycache and the files will be recreated.
