### ISSUE TITLE
cdn server url twice in merged css url and returns 404

### ISSUE THREAD

**Issue by kuldeepkaushik** [fooman/speedster#21]
Hi 

we are using cdn server and we see that the url provided for merged js is fine but in css it's adding store url in the first css twice . For example 

http://newdev.test.com/skin/m/1460751109/newdev.test.com/skin/frontend/mainstreet/default/css/styles.css,/skin/frontend/mainstreet/default/css/widgets.css,.....

you will see newdev.test.com twice . Can you please help on this .

Thanks 
Kuldeep

**Comment by fooman** [comment]
Hi @kuldeepkaushik the Speedster extesnsion does not support CDN configurations. If you are interested in this and your CDN supports pulling from origin then I suggest taking a look at https://github.com/fooman/speedsteradvanced
