### ISSUE TITLE
site design breaks down when enabling extension (Justselling_Assetminify)

### ISSUE THREAD

**Issue by vijendrap** [fooman/speedster#28]
We have Justselling_Assetminify extension installed on our website which is probably the older version of this fooman_speedster extension. 
On enabling the extension, the frontend and backend of the site is breaking down completely after enabling. The css/js urls are getting wrongly generated. We use cdn and also cloudflare on our setups.
So, please confirm if the extension does not work with cdn configuration (as mentioned in one of the tickets) and let us know if there's any work-around to fix it.

**Comment by fooman** [comment]
Using a cdn with this extension is not supported. I suggest taking a look at SpeedsterAdvanced to see if that covers your use case https://github.com/fooman/speedsteradvanced
