### ISSUE TITLE
Fooman_SpeedsterAdvanced `get_parent_class($this)` issue.

### ISSUE THREAD

**Issue by vovayatsyuk** [fooman/speedster#7]
It's a report about issue in SpeedsterAdvanced 0.8.9:

Can you replace the following code in rewritten `Design_Package` model:
```
method_exists(get_parent_class($this), '__construct')
```

with:

```
method_exists('Mage_Core_Model_Design_Package', '__construct')
```

This will fix the third-party compatibility issue, when some extension is trying to use your model:
```
Some_Third_Party_Extension_Model extends Fooman_SpeedsterAdvanced_Model {}
```

In this case `$this` is the `Some_Third_Party_Extension_Model` and `get_parent_class($this)`, called in your constructor will return `Fooman_SpeedsterAdvanced_Model` and `method_exists` will return true, but parent::__construct will result in fatal error on old Magento.

**Comment by fooman** [comment]
Closing as has been available for a while https://github.com/fooman/speedsteradvanced/blob/master/app/code/community/Fooman/SpeedsterAdvanced/Model/Core/Design/Package.php#L37
